version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASS: password
      MONGODB_DATABASE: product_service
    volumes:
      - ./mongodb:/data/db
      