spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
server.port=9081
inventory.url=http://localhost:9082
# swagger config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# end swagger config



# Actuator Endpoints
## This property explicitly enables the health indicator for circuit breakers within Spring Boot Actuator's /actuator/health endpoint. This means that when you check your application's health, Actuator will include information about the status of your configured circuit breakers (e.g., whether they are CLOSED, OPEN, HALF_OPEN). 
management.health.circuitbreakers.enabled=true
##  This is a broad setting that exposes all available Actuator endpoints over the web. By default, only a few endpoints like health and info are exposed. Using * makes all endpoints accessible, including those that provide detailed metrics, environment information, and in this context, specific circuit breaker metrics. Be cautious with this in production environments as it can expose sensitive information.
management.endpoints.web.exposure.include=*
##  This property configures the /actuator/health endpoint to always show full details about the health status of various components. By default, some details might be hidden for security reasons unless the user is authenticated or has a specific role. Setting it to always ensures that you get the most granular health information, including details about your circuit breakers' states. 
management.endpoint.health.show-details=always

# Resilience4j Properties (For Inventory Client)
## This property ensures that Resilience4j integrates its circuit breaker status with Spring Boot Actuator's health endpoint. When this is true (and management.health.circuitbreakers.enabled is also true), Actuator's health check will display the current state of your Resilience4j circuit breakers. This is crucial for monitoring their health.
resilience4j.circuitbreaker.configs.i.registerHealthIndicator=true
## This defines how Resilience4j tracks the calls to determine the failure rate.
###COUNT_BASED: The circuit breaker looks at a fixed number of most recent calls (defined by slidingWindowSize) to calculate the failure rate. It doesn't care about the time when these calls occurred, only their count. \ud83d\udd22
###TIME_BASED (alternative): The circuit breaker looks at calls within a fixed time window (e.g., the last 10 seconds) to calculate the failure rate.
resilience4j.circuitbreaker.configs.inventory.slidingWindowType=COUNT_BASED
## When slidingWindowType is COUNT_BASED, this property sets the number of calls that the circuit breaker will consider to calculate the failure rate. In this case, it will look at the last 10 calls. 	
resilience4j.circuitbreaker.configs.inventory.slidingWindowSize=10
## This is a crucial threshold. If the percentage of failed calls within the slidingWindowSize exceeds this value (60%), the circuit breaker will transition from CLOSED to OPEN state. So, if 6 out of the last minimumNumberOfCalls (or above) calls fail, the circuit will open.
resilience4j.circuitbreaker.configs.inventory.failureRateThreshold=60
## This defines how long the circuit breaker will remain in the OPEN state. When OPEN, all calls to the protected service are immediately rejected without even attempting the call. After this 5s duration, the circuit breaker will automatically transition to the HALF_OPEN state. There are 3 state:
## Close: allow all calls to external service
## Open: deny all calls to external service
## Half-Open: allow a small calls to test and determine to change status to Close Or Open.
resilience4j.circuitbreaker.configs.inventory.waitDurationInOpenState=5s
## When the circuit breaker is in the HALF_OPEN state, it allows a limited number of calls (3 in this case) to pass through to the protected service. This is a "trial" period. If all of 3 trial calls are successful, the circuit will transition back to CLOSED; if one of them fail, it will return to OPEN.
resilience4j.circuitbreaker.configs.inventory.permittedNumberOfCallsInHalfOpenState=3
## This property, when set to true, ensures that the circuit breaker automatically transitions from OPEN to HALF_OPEN after the waitDurationInOpenState has elapsed. If this were false, the transition would require a manual reset or a different event.
resilience4j.circuitbreaker.configs.inventory.automaticTransitionFromOpenToHalfOpenEnabled=true
## This is the absolute number of calls that must have occurred within the slidingWindowSize before the failureRateThreshold is even considered. 
resilience4j.circuitbreaker.configs.inventory.minimumNumberOfCalls=5

# Resilience4j Timeout Properties
## if external service isn't returning response in 3 seconds, then the Resilience4j will recognize it as fail call and increase counter for circuit breaker
resilience4j.timelimiter.configs.inventory.timeout-duration=3s

# Resilience4j Retry Properties
## After 2s not receive the response from external service, it will retry and wait for 2s. The maximum number of retry is 3. 
## After that, it will be moved to to timeout step of Resilience4j  
resilience4j.retry.configs.inventory.max-attemps=3
resilience4j.retry.configs.inventory.wait-duration=2s
# Kafka config
## Config host of kafka server
spring.kafka.bootstrap-servers=localhost:9092
## Config default topic
spring.kafka.template.default-topic=order-placed
## Config key serializer (when send to the kafka)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
## Config value serializer (when send to the kafka)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
